dist: xenial
language: python
python:
  - 3.6
before_install:
 - pip install --only-binary=all scipy cython coveralls
install:
 - python setup.py install
script:
 - python setup.py test
 - denovonear cluster --in data/example_de_novos.txt --out output.txt
 - denovonear transcripts --de-novos data/example_de_novos.txt --out output.txt
     --all-transcripts
 - denovonear rates --genes data/example_gene_ids.txt --out output.txt
 - python -m coverage run --source=./denovonear -m unittest discover
after_success:
 - coveralls
