language: python
python:
  - 3.3
  - 2.7
before_install:
 - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
 - python setup.py install
script:
 - python setup.py test
 - "python scripts/clustering.py \
     --in data/example_de_novos.txt \
     --rates data/forSanger_1KG_mutation_rate_table.txt \
     --out output.txt"
