language: python
python:
  - 3.3
  - 2.7
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      - libatlas-base-dev
      - gfortran
before_install:
 - mkdir -p $HOME/.cache/pip/wheels
 # build wheel only if none present
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels scipy
 - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels pysam
 # now install from it
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels scipy
 - pip install --no-index --find-links=$HOME/.cache/pip/wheels pysam
install:
 - python setup.py install
script:
 - python setup.py test
 - "python scripts/clustering.py \
     --in data/example_de_novos.txt \
     --rates data/forSanger_1KG_mutation_rate_table.txt \
     --out output.txt"
 - "python scripts/identify_transcripts.py \
     --de-novos data/example_de_novos.txt \
     --out output.txt \
     --all-transcripts"
 - "python scripts/construct_mutation_rates.py \
     --transcripts data/example_transcript_ids.txt \
     --rates data/forSanger_1KG_mutation_rate_table.txt \
     --out output.txt"
