language: python
python:
  - 2.7
  - 3.4
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libatlas-base-dev
      - gfortran
      - gcc-4.9
      - g++-4.9
env:
    - CC=gcc-4.9 CXX=g++-4.9
before_install:
 - pip install --upgrade pip setuptools wheel
 - pip install --only-binary=all scipy cython coveralls
install:
 - python setup.py install
script:
 - python setup.py test
 - "python scripts/clustering.py \
     --in data/example_de_novos.txt \
     --out output.txt"
 - "python scripts/identify_transcripts.py \
     --de-novos data/example_de_novos.txt \
     --out output.txt \
     --all-transcripts"
 - "python scripts/construct_mutation_rates.py \
     --transcripts data/example_transcript_ids.txt \
     --out output.txt"
 - python -m coverage run --source=./denovonear -m unittest discover
after_success:
 - coveralls
